services:
  timescaledb:
    #hub.docker.com -> timescaledb
    image: timescale/timescaledb:latest-pg16 #latest TimescaleDB image compatible with PostgreSQL 16.
    # environment: 
    #   POSTGRES_USER: your_username
    #   POSTGRES_PASSWORD: your_password
    #   POSTGRES_DB: your_database
    env_file:
      - .env.db
    ports:
      - "5555:5432" #localhost:5555
    volumes: 
      - timescale_data:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  timescale_data:
